const ingredients = [
  { "id": 0, "name": "all-purpose flour" },
  { "id": 1, "name": "almond flour" },
  { "id": 2, "name": "almonds" },
  { "id": 3, "name": "apple" },
  { "id": 4, "name": "applesauce" },
  { "id": 5, "name": "avocado" },
  { "id": 6, "name": "balsamic vinegar" },
  { "id": 7, "name": "banana" },
  { "id": 8, "name": "basil" },
  { "id": 9, "name": "beans" },
  { "id": 10, "name": "beef" },
  { "id": 11, "name": "bell pepper" },
  { "id": 12, "name": "blueberries" },
  { "id": 13, "name": "bread" },
  { "id": 14, "name": "breadcrumbs" },
  { "id": 15, "name": "bread flour" },
  { "id": 16, "name": "brown sugar" },
  { "id": 17, "name": "butter" },
  { "id": 18, "name": "buttermilk" },
  { "id": 19, "name": "cake flour" },
  { "id": 20, "name": "carrot" },
  { "id": 21, "name": "celery" },
  { "id": 22, "name": "cheese" },
  { "id": 23, "name": "chicken" },
  { "id": 24, "name": "chicken broth" },
  { "id": 25, "name": "chocolate" },
  { "id": 26, "name": "cinnamon" },
  { "id": 27, "name": "cilantro" },
  { "id": 28, "name": "cocoa powder" },
  { "id": 29, "name": "coconut milk" },
  { "id": 30, "name": "coffee" },
  { "id": 31, "name": "corn" },
  { "id": 32, "name": "cornflour" },
  { "id": 33, "name": "cornmeal" },
  { "id": 34, "name": "cornstarch" },
  { "id": 35, "name": "cottage cheese" },
  { "id": 36, "name": "cream cheese" },
  { "id": 37, "name": "crushed tomatoes" },
  { "id": 38, "name": "curry paste/roux" },
  { "id": 39, "name": "dashi" },
  { "id": 40, "name": "diced tomatoes" },
  { "id": 41, "name": "dijon mustard" },
  { "id": 42, "name": "edamame" },
  { "id": 43, "name": "egg" },
  { "id": 44, "name": "egg whites" },
  { "id": 45, "name": "espresso powder" },
  { "id": 46, "name": "evaporated milk" },
  { "id": 47, "name": "extra firm tofu" },
  { "id": 48, "name": "flaxseed" },
  { "id": 49, "name": "garlic" },
  { "id": 50, "name": "ginger" },
  { "id": 51, "name": "granulated sugar" },
  { "id": 52, "name": "heavy cream" },
  { "id": 53, "name": "honey" },
  { "id": 54, "name": "lemon" },
  { "id": 55, "name": "lemongrass" },
  { "id": 56, "name": "lettuce" },
  { "id": 57, "name": "maple syrup" },
  { "id": 58, "name": "marshmallow fluff" },
  { "id": 59, "name": "milk" },
  { "id": 60, "name": "mirin" },
  { "id": 61, "name": "molasses" },
  { "id": 62, "name": "oat flour" },
  { "id": 63, "name": "oil" },
  { "id": 64, "name": "old-fashioned rolled oats" },
  { "id": 65, "name": "onion" },
  { "id": 66, "name": "orange" },
  { "id": 67, "name": "pasta" },
  { "id": 68, "name": "pasta sauce" },
  { "id": 69, "name": "peas" },
  { "id": 70, "name": "pecans" },
  { "id": 71, "name": "peanut butter" },
  { "id": 72, "name": "pineapple" },
  { "id": 73, "name": "poppy seeds" },
  { "id": 74, "name": "potato" },
  { "id": 75, "name": "powdered sugar" },
  { "id": 76, "name": "prosciutto" },
  { "id": 77, "name": "pumpkin purée" },
  { "id": 78, "name": "quick oats" },
  { "id": 79, "name": "raisins" },
  { "id": 80, "name": "raspberries" },
  { "id": 81, "name": "rice" },
  { "id": 82, "name": "ricotta" },
  { "id": 83, "name": "sake" },
  { "id": 84, "name": "salsa" },
  { "id": 85, "name": "sausage" },
  { "id": 86, "name": "scallions" },
  { "id": 87, "name": "shallot" },
  { "id": 88, "name": "shortening" },
  { "id": 89, "name": "shredded coconut" },
  { "id": 90, "name": "silken tofu" },
  { "id": 91, "name": "sour cream" },
  { "id": 92, "name": "soy sauce" },
  { "id": 93, "name": "spinach" },
  { "id": 94, "name": "taco sauce" },
  { "id": 95, "name": "tapioca flour" },
  { "id": 96, "name": "tomato" },
  { "id": 97, "name": "tomato paste" },
  { "id": 98, "name": "tortilla" },
  { "id": 99, "name": "tortilla chips" },
  { "id": 100, "name": "turkey" },
  { "id": 101, "name": "walnuts" },
  { "id": 102, "name": "wheat bran" },
  { "id": 103, "name": "white chocolate" },
  { "id": 104, "name": "white vinegar" },
  { "id": 105, "name": "white wine" },
  { "id": 106, "name": "white wine vinegar" },
  { "id": 107, "name": "whole wheat flour" },
  { "id": 108, "name": "yeast" },
  { "id": 109, "name": "yogurt" },
  { "id": 110, "name": "zucchini" }
];

module.exports = { ingredients };